import { Car } from './car';

export const DUMMY_CARS: Car[] = [
    {
      carId: 'c1',
      owner: 'Dealer',
      make: 'Nissan',
      model: 'Altima',
      url: '',
      price: 12384,
    },
    {
      carId: 'c2',
      owner: 'Dealer',
      make: 'Nissan',
      model: 'Altima',
      url: '',
      price: 12384,
    },
    {
      carId: 'c3',
      owner: 'Dealer',
      make: 'Nissan',
      model: 'Altima',
      url: '',
      price: 12384,
    },
    {
      carId: 'c4',
      owner: 'Dealer',
      make: 'Nissan',
      model: 'Altima',
      url: '',
      price: 12384,
    },
    {
      carId: 'c5',
      owner: 'Dealer',
      make: 'Nissan',
      model: 'Altima',
      url: '',
      price: 12384,
    },
    {
      carId: 'c6',
      owner: 'Dealer',
      make: 'Nissan',
      model: 'Altima',
      url: '',
      price: 12384,
    },
    {
      carId: 'c7',
      owner: 'Dealer',
      make: 'Nissan',
      model: 'Altima',
      url: '',
      price: 12384,
    },
    {
      carId: 'c8',
      owner: 'Dealer',
      make: 'Nissan',
      model: 'Altima',
      url: '',
      price: 12384,
    },
    {
      carId: 'c9',
      owner: 'Dealer',
      make: 'Nissan',
      model: 'Altima',
      url: '',
      price: 12384,
    },
    {
      carId: 'c10',
      owner: 'Dealer',
      make: 'Nissan',
      model: 'Altima',
      url: '',
      price: 12384,
    },
  ];